// <auto-generated />
using LibraryData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Store_Management_Data.Migrations
{
    [DbContext(typeof(StoreManagementContext))]
    partial class StoreManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LibraryData.Models.User", b =>
                {
                    b.Property<int>("U_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("U_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Pass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("U_Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("U_Zipcode")
                        .HasColumnType("int");

                    b.HasKey("U_Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
